from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import FileViewSet

# Create a router and register our viewset with it.
# DefaultRouter automatically generates the URL patterns for a viewset,
# including list, create, retrieve, update, and destroy actions.
router = DefaultRouter()
router.register(r'files', FileViewSet, basename='file') # Use basename to avoid conflicts

# Define the API URL patterns.
urlpatterns = [
    # Custom route for getting the status of a specific file.
    # Maps GET requests to the 'get_file_status' action in the FileViewSet.
    path('files/<uuid:pk>/status/', FileViewSet.as_view({'get': 'get_file_status'}), name='file-status'),
    
    # Custom route for getting the total storage savings from deduplication.
    # Maps GET requests to the 'total_saving_size' action in the FileViewSet.
    path('files/total_saving_size/', FileViewSet.as_view({'get': 'total_saving_size'}), name='total-saving-size'),
    
    # Include the URLs generated by the DefaultRouter.
    # This will create routes like /files/, /files/<pk>/, etc.
    path('', include(router.urls))
]