# Generated by Django 4.2.22 on 2025-06-10 05:06

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_make_file_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=files.models.file_upload_path),
        ),
    ]
