# Generated by Django 4.2.22 on 2025-06-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_file_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='original_filename',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file_type', 'size'], name='files_file_file_ty_421fd5_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['size', 'uploaded_at'], name='files_file_size_4a9580_idx'),
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['file'], name='files_file_file_fb6e81_idx'),
        ),
    ]
